### ISSUE TITLE
Idea: Add this to minikanren.org

### ISSUE THREAD

**Issue by pianoJames** [jams2/microkanren#7]
Hello,
I thought you might want to add a link to your implementation on [minikanren.org](http://minikanren.org). I think you'd submit a pull request on [their repository](https://github.com/miniKanren/miniKanren_org-website/), probably near [this line](https://github.com/miniKanren/miniKanren_org-website/blob/master/index.html#L585).

Thanks!

**Comment by jams2** [comment]
Thanks for the suggestion. I've opened a PR [here](https://github.com/miniKanren/miniKanren_org-website/pull/39)
